### PR TITLE
Fixed: Objects are not valid as a React child error for complex JSON …

### PR DESCRIPTION
**Pull request by rajdude0**
isValuePrimitive check was being done for the key but not for the value of the object

### CODE REVIEW

**Comment by SunKD** [comment]
Can anyone merge this to this change? I have the same issue and this change fixed my issue as well.

**Comment by pvannierop** [comment]
@SunKD @taichoup @rajdude0 Merged!

**Comment by taichoup** [comment]
Thanks!

**Comment by SunKD** [comment]
@pvannierop In order to use this changes through npm package, should it be published as release? I tried removing and reinstalling the package but seems like that didn't help anything.

**Pull request merged**
